name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run lint
      - name: build
        run: npm run build:back
      - name: test
        run: npm run test
        env:
          DB_CONNECTION_TEST: ${{secrets.DB_CONNECTION_TEST}}
          JWT_SECRET: ${{secrets.JWT_SECRET}}
          JWT_EXPIRES_IN: ${{secrets.JWT_EXPIRES_IN}}
          STRIPE_SECRET_KEY: ${{secrets.STRIPE_SECRET_KEY}}
      - name: debloy
        if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, 'skip')}}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'powerful-mountain-41188'
          heroku_email: 'ville.l.alatalo@gmail.com'
          healthcheck: 'https://powerful-mountain-41188.herokuapp.com/health'
          checkstring: 'healthcheck ok'
          rollbackonhealthcheckfailed: true
        env:
          HD_DB_CONNECTION: ${{secrets.DB_CONNECTION}}
          HD_JWT_SECRET: ${{secrets.JWT_SECRET}}
          HD_JWT_EXPIRES_IN: ${{secrets.JWT_EXPIRES_IN}}
          HD_EMAIL_PASSWORD_PROD: ${{secrets.EMAIL_PASSWORD_PROD}}
          HD_STRIPE_SECRET_KEY: ${{secrets.STRIPE_SECRET_KEY}}
